In [1]:
print("Hello Spectrics Solutions")

Hello Spectrics Solutions


In [2]:
#print("Hello, spectrics!")
print("Hello, code!")

Hello, code!


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [4]:
print(arr[1])

2


In [5]:
type(arr)

numpy.ndarray

In [6]:
import numpy as np

# Creating arrays
arr_1d = np.array([1, 2, 3, 4, 5])  # 1D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array

print("1D Array:")
print(arr_1d)
print("2D Array:")
print(arr_2d)

1D Array:
[1 2 3 4 5]
2D Array:
[[1 2 3]
 [4 5 6]]


In [7]:
# Arithmetic operations
addition = arr_1d + 2  # Add 2 to each element
multiplication = arr_2d * 2  # Multiply each element by 2

print("\nArray After Addition:")
print(addition)
print("Array After Multiplication:")
print(multiplication)


Array After Addition:
[3 4 5 6 7]
Array After Multiplication:
[[ 2  4  6]
 [ 8 10 12]]


In [8]:
# Accessing elements
print("\nElement at index 2 in 1D Array:")

print(arr_1d[2])  # Access third element of 1D array
print("Element at row 1 column 2 in 2D Array:")
print(arr_2d[1, 2])  # Access element from second row, third column



Element at index 2 in 1D Array:
3
Element at row 1 column 2 in 2D Array:
6


In [9]:
# Slicing
print("\nSliced Array from 1D Array:")
print(arr_1d[1:4])  # Slice from index 1 to 3


Sliced Array from 1D Array:
[2 3 4]


In [11]:
# Reshaping arrays
reshaped_array = np.reshape(arr_2d, (3,2))
print("\nReshaped 2D Array (2x2):")
print(reshaped_array)



Reshaped 2D Array (2x2):
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# Statistical functions
mean_value = np.mean(arr_1d)
max_value = np.max(arr_2d)
std_dev = np.std(arr_1d)



print("\nStatistics:")
print("Mean of 1D Array:", mean_value)
print("Maximum in 2D Array:", max_value)
print("Standard Deviation of 1D Array:", std_dev)


Statistics:
Mean of 1D Array: 3.0
Maximum in 2D Array: 6
Standard Deviation of 1D Array: 1.4142135623730951


In [ ]:
# Creating specialized arrays
zeros_array = np.zeros((2, 3))  # 2x3 array of zeros
ones_array = np.ones((3, 2))  # 3x2 array of ones
identity_matrix = np.eye(3)  # 3x3 identity matrix

print("\nSpecial Arrays:")
print("Zeros Array:")
print(zeros_array)
print("Ones Array:")
print(ones_array)
print("Identity Matrix:")
print(identity_matrix)


Special Arrays:
Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
[[1. 1.]
 [1. 1.]
 [1. 1.]]
Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np

original = np.array([10, 20, 30])
copy_array = original.copy()

copy_array[0] = 99  # Modify the copy
print("Original Array:", original)  # Unchanged
print("Copy Array:", copy_array)    # Modified

Original Array: [10 20 30]
Copy Array: [99 20 30]


In [ ]:
import numpy as np

original = np.array([10, 20, 30])
view_array = original.view()

view_array[0] = 99  # Modify the view
print("Original Array:", original)  # Affected
print("View Array:", view_array)    # Modified


Original Array: [99 20 30]
View Array: [99 20 30]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  #shape

(2, 3)


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.concatenate((arr1, arr2))
print(result) 

[1 2 3 4 5 6]


In [ ]:
#The concatenate() function joins arrays along an existing axis.
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
result = np.concatenate((arr1, arr2), axis=0)
print(result)
# Output:
# [[1 2]
#  [3 4]
#  [5 6]]


[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#The stack() function joins arrays along a new axis.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.stack((arr1, arr2), axis=0)  # Stack as rows
print(result)

[[1 2 3]
 [4 5 6]]


In [ ]:
result = np.stack((arr1, arr2), axis=1)  # Stack as columns
print(result)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
#The hstack() function stacks arrays horizontally (column-wise).
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.hstack((arr1, arr2))
print(result) 

[1 2 3 4 5 6]


In [ ]:
#2-d array
arr1 = np.array([[1], [3]])
arr2 = np.array([[2], [4]])
result = np.hstack((arr1, arr2))
print(result)


[[1 2]
 [3 4]]


In [ ]:
#The vstack() function stacks arrays vertically (row-wise).
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.vstack((arr1, arr2))
print(result)

[[1 2 3]
 [4 5 6]]


In [ ]:
#The dstack() function stacks arrays depth-wise (along the third dimension).
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.dstack((arr1, arr2))
print(result)

[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
#The split() function splits an array into multiple sub-arrays along a specified axis.
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
result = np.split(arr, 3)  # Split into 3 equal parts
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
#Use indices to specify uneven splits:
result = np.split(arr, [2, 4])  # Split at indices 2 and 4
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
#The hsplit() function splits an array horizontally (column-wise).
arr = np.array([[1, 2, 3], [4, 5, 6]])
result = np.hsplit(arr, 3)  # Split into 3 columns
print(result)

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [ ]:
#The vsplit() function splits an array vertically (row-wise).
arr = np.array([[1, 2, 3], [4, 5, 6]])
result = np.vsplit(arr, 2)  # Split into 2 rows
print(result)

[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [ ]:
#The dsplit() function splits an array depth-wise (along the third dimension).
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
result = np.dsplit(arr, 2)  # Split into 2 depth-wise slices
print(result)

[array([[[1],
        [3]],

       [[5],
        [7]]]), array([[[2],
        [4]],

       [[6],
        [8]]])]


In [ ]:
# Creating an array
arr = np.array([1, 2, 3, 4, 5, 6])

# Mathematical Operations
# Power and exponential functions
powers = np.power(arr, 2)  # Square of each element
exponentials = np.exp(arr)  # Exponential of each element

print("Powers of Array Elements:")
print(powers)
print("Exponential of Array Elements:")
print(exponentials)

Powers of Array Elements:
[ 1  4  9 16 25 36]
Exponential of Array Elements:
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]


In [ ]:
# Trigonometric Functions
sine_values = np.sin(arr * np.pi / 180)  # Sine of each element, assuming the input is in degrees
cosine_values = np.cos(arr * np.pi / 180)  # Cosine of each element

print("\nSine Values:")
print(sine_values)
print("Cosine Values:")
print(cosine_values)


Sine Values:
[0.01745241 0.0348995  0.05233596 0.06975647 0.08715574 0.10452846]
Cosine Values:
[0.9998477  0.99939083 0.99862953 0.99756405 0.9961947  0.9945219 ]


In [ ]:
# Statistical Functions
mean_val = np.mean(arr)
median_val = np.median(arr)
variance_val = np.var(arr)

print("\nStatistics of the Array:")
print(f"Mean: {mean_val}, Median: {median_val}, Variance: {variance_val}")


Statistics of the Array:
Mean: 3.5, Median: 3.5, Variance: 2.9166666666666665


In [ ]:
# Linear Algebra
# Creating two matrices for demonstrating matrix operations
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])

# Matrix Multiplication
matrix_product = np.dot(A, B)

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("\nMatrix A:")
print(A)
print("Matrix B:")
print(B)
print("Matrix Product of A and B:")
print(matrix_product)
print("Eigenvalues of Matrix A:")
print(eigenvalues)
print("Eigenvectors of Matrix A:")
print(eigenvectors)



Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[2 0]
 [1 2]]
Matrix Product of A and B:
[[ 4  4]
 [10  8]]
Eigenvalues of Matrix A:
[-0.37228132  5.37228132]
Eigenvectors of Matrix A:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
# Solving a system of linear equations
# Consider the system: 3x + 4y = 5 and 2x - y = 1
coefficients = np.array([[3, 4], [2, -1]])
constants = np.array([5, 1])

solutions = np.linalg.solve(coefficients, constants)
print("\nSolution to the system of equations (3x + 4y = 5, 2x - y = 1):")
print(solutions)


Solution to the system of equations (3x + 4y = 5, 2x - y = 1):
[0.81818182 0.63636364]


In [ ]:
# Random Sampling for Statistics
# Generate 10 random samples from a normal distribution with mean 0 and standard deviation 1
random_samples = np.random.normal(0, 1, 10)
print("\nRandom Samples from a Normal Distribution:")
print(random_samples)


Random Samples from a Normal Distribution:
[-1.81779659 -0.09636788 -1.10150761 -1.96330021  1.24427419  0.04381252
  0.26960023 -0.69589679  0.732057    1.85736454]


In [ ]:
import random
print(random.random())  # Output: A random number between 0 and 1


0.6534505628335295


In [ ]:
#random.randint(a, b): Returns a random integer between a and b (inclusive).
print(random.randint(1, 10))  # Output: Random integer between 1 and 10


10


In [ ]:
#random.uniform(a, b): Returns a random float between a and b.
print(random.uniform(1, 10))  # Output: Random float between 1 and 10

3.474286446005295


In [ ]:
#random.choice(sequence): Randomly selects an element from a non-empty sequence (e.g., list, tuple).
my_list = [1, 2, 3, 4, 5]
print(random.choice(my_list))

3


In [ ]:
#random.shuffle(sequence): Randomly shuffles the elements of a list in place.
random.shuffle(my_list)
print(my_list) 

[1, 4, 5, 3, 2]


In [ ]:
#numpy.random.rand(): Returns an array of random numbers between 0 and 1.
import numpy as np
arr = np.random.rand(3, 2)  # 3x2 array of random floats between 0 and 1
print(arr)

[[0.21469017 0.669559  ]
 [0.87311069 0.00187485]
 [0.46682799 0.75097693]]


In [ ]:
#numpy.random.randint(low, high, size): Returns a random integer array between low and high (exclusive of high).
arr = np.random.randint(1, 10, size=(2, 3))  # 2x3 array of random integers between 1 and 10
print(arr)

[[2 1 6]
 [2 6 2]]


In [ ]:
# numpy.random.uniform(low, high, size): Returns an array of random floats between low and high.
arr = np.random.uniform(1, 10, size=(2, 3))  # 2x3 array of random floats between 1 and 10
print(arr)

[[2.22001137 9.68120893 6.12282334]
 [6.42317002 5.66219873 8.04624643]]


In [ ]:
#numpy.random.choice(a, size, replace, p): Randomly selects elements from an array.
arr = np.array([1, 2, 3, 4, 5])
result = np.random.choice(arr, size=3, replace=False)  # Select 3 elements without replacement
print(result)

[1 3 4]


In [ ]:
#numpy.random.normal(loc, scale, size): Generates random numbers from a normal (Gaussian) distribution.
arr = np.random.normal(0, 1, 5)  # 5 random numbers from a normal distribution with mean=0 and std=1
print(arr)

[ 1.1837143   0.87875852  2.33444476  0.59314017 -0.38511166]


In [ ]:
# Using random.seed():
random.seed(42)
print(random.random()) # Output: Always the same value for the same seed

0.6394267984578837


In [ ]:
np.random.seed(42)
print(np.random.rand(2, 2))  # Output: Always the same array for the same seed

[[0.37454012 0.95071431]
 [0.73199394 0.59865848]]


In [ ]:
import numpy as np

# Simulate a dataset with 100 samples and 3 features
data = np.random.rand(100, 3)  # 100 rows, 3 columns of random floats between 0 and 1
print(data)

# Generate random labels (0 or 1)
labels = np.random.randint(0, 2, size=100)  # Random binary labels
print(labels)

[[0.15601864 0.15599452 0.05808361]
 [0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264]
 [0.21233911 0.18182497 0.18340451]
 [0.30424224 0.52475643 0.43194502]
 [0.29122914 0.61185289 0.13949386]
 [0.29214465 0.36636184 0.45606998]
 [0.78517596 0.19967378 0.51423444]
 [0.59241457 0.04645041 0.60754485]
 [0.17052412 0.06505159 0.94888554]
 [0.96563203 0.80839735 0.30461377]
 [0.09767211 0.68423303 0.44015249]
 [0.12203823 0.49517691 0.03438852]
 [0.9093204  0.25877998 0.66252228]
 [0.31171108 0.52006802 0.54671028]
 [0.18485446 0.96958463 0.77513282]
 [0.93949894 0.89482735 0.59789998]
 [0.92187424 0.0884925  0.19598286]
 [0.04522729 0.32533033 0.38867729]
 [0.27134903 0.82873751 0.35675333]
 [0.28093451 0.54269608 0.14092422]
 [0.80219698 0.07455064 0.98688694]
 [0.77224477 0.19871568 0.00552212]
 [0.81546143 0.70685734 0.72900717]
 [0.77127035 0.07404465 0.35846573]
 [0.11586906 0.86310343 0.62329813]
 [0.33089802 0.06355835 0.31098232]
 [0.32518332 0.72960618 0.63